name: melos_example

packages:
  - packages/**
  - apps/**

scripts:
  lint:all:
    run: melos run analyze && melos run format
    description: Run all static analysis checks

  analyze:
    run: |
      melos exec -c 5 -- \
        dart analyze . --fatal-infos

  format:
    run: |
      melos exec -c 5 -- \
        dart format .

  build:android:
    run: |
      melos exec -c 5 -- \
        flutter build apk
    select-package:
      scope: "app_a*"