name: melos_example

packages:
  - packages/**
  - apps/**

scripts:

  get:all:
    run: melos run get:libs && melos run get:apps

  get:libs:
    run: |
      melos exec -c 5 -- \
        dart pub get

  get:apps:
    run: |
      melos exec -c 5 -- \
        dart pub get

  lint:all:
    run: melos run analyze && melos run format
    description: Run all static analysis checks

  analyze:
    run: |
      melos exec -c 5 -- \
        dart analyze . --fatal-infos

  format:
    run: |
      melos exec -c 5 -- \
        dart format .